# Generated by Django 4.1.1 on 2022-10-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_contact_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_typename', models.CharField(max_length=30)),
                ('typename_bgpic', models.ImageField(upload_to='')),
            ],
        ),
    ]
