# Generated by Django 4.1.1 on 2022-10-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallery',
            new_name='gallery1',
        ),
    ]
