# Generated by Django 4.1.1 on 2022-10-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_gallery_gallery1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery1',
            name='typename_bgpic',
            field=models.ImageField(height_field=500, upload_to='temp', width_field=800),
        ),
    ]
