# Generated by Django 4.1.1 on 2022-10-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_gallery1_typename_bgpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery1',
            name='typename_bgpic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
