# Generated by Django 4.1.1 on 2022-10-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_gallery1_typename_bgpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery1',
            name='typename_bgpic',
            field=models.ImageField(upload_to='static'),
        ),
        migrations.CreateModel(
            name='gallery_subitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subitem_img', models.ImageField(upload_to='static')),
                ('gallery1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.gallery1')),
            ],
        ),
    ]
