# Generated by Django 4.1.1 on 2022-10-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_gallery1_typename_bgpic_gallery_subitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery1',
            name='typename_bgpic',
            field=models.ImageField(upload_to='static/gallerypic'),
        ),
        migrations.AlterField(
            model_name='gallery_subitem',
            name='subitem_img',
            field=models.ImageField(upload_to='static/sub_gallery'),
        ),
    ]
