# Generated by Django 4.1.1 on 2022-11-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_gallery_subitem_gallery1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_subitem',
            name='gallery1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.gallery1'),
        ),
    ]
