# Generated by Django 4.1.1 on 2023-01-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_gallery_subitem_image_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_value', models.FileField(upload_to='static/gallerypic')),
            ],
        ),
    ]
