# Generated by Django 4.1.1 on 2023-01-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_doc_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_files',
            name='file_value',
            field=models.FileField(upload_to='static/docs'),
        ),
    ]
