# Generated by Django 4.1.1 on 2023-01-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_doc_files_file_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doc_files',
            new_name='Doc_file',
        ),
    ]
