# Generated by Django 4.1.1 on 2023-01-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_doc_files_doc_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery_subitem',
            old_name='gallery1',
            new_name='main_gallery',
        ),
    ]
