# Generated by Django 4.1.1 on 2023-01-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_gallery1_gallery_subitem_main_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery_subitem',
            old_name='main_gallery',
            new_name='subitem_id',
        ),
        migrations.AlterField(
            model_name='gallery1',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
