# Generated by Django 4.1.1 on 2023-01-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_main_gallery_gallery_subitem_subitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery1',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
