# Generated by Django 4.1.1 on 2023-01-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_gallery1_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery_subitem',
            old_name='subitem_id',
            new_name='subitem',
        ),
    ]
