# Generated by Django 4.1.1 on 2023-03-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_subitem_id_gallery_subitem_subitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default=False, max_length=13, null=True),
        ),
    ]
